### ISSUE TITLE
Manjaro - XFCE

### ISSUE THREAD

**Issue by en3r0** [rebootl/speech-typer-gui#1]
Any idea how I could get this to run under Manjaro on XFCE?

**Comment by rebootl** [comment]
Hi, I think you have to install `tk` using pacman or the gui manager.

Then you can follow the instructions under: https://github.com/rebootl/linux-speech-typer#installation

That should work since i'm using Manjaro myself but with kde instead of xfce. :)

**Comment by en3r0** [comment]
Thanks, I was able to see that tk was already installed on my system.
